{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-exercise-app.fullname" . }}-secrets
  labels:
    {{- include "wiz-exercise-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.mongodb.host .Values.mongodb.username .Values.mongodb.password }}
  mongodb-uri: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.host }}:{{ .Values.mongodb.port }}/{{ .Values.mongodb.database }}"
  {{- else }}
  mongodb-uri: ""
  {{- end }}
  {{- if .Values.secrets.secretKey }}
  secret-key: {{ .Values.secrets.secretKey | quote }}
  {{- else }}
  secret-key: "change-me-in-production"
  {{- end }}
{{- end }}
