image:
  repository: 180294187104.dkr.ecr.us-east-1.amazonaws.com/wiz-securelabs-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/tags: Project=wiz-tech-exercise,Team=SecureLabs
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

mongodb:
  uri: "mongodb://admin:SuperSecretPassword123!@mongo-ip:27017" # To be replaced at deploy time

# Weakness: App runs with cluster-admin privileges (intentional vulnerability)
serviceAccount:
  create: true
  name: "wiz-securelabs-app-sa"

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"




