image:
  repository: 180294187104.dkr.ecr.us-east-1.amazonaws.com/wiz-tech-exercise-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP # Changed from LoadBalancer to ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix

mongodb:
  uri: "mongodb://admin:SuperSecretPassword123!@mongo-ip:27017" # To be replaced

# Weakness: App runs as cluster-admin
serviceAccount:
  create: true
  name: "wiz-app-sa"


